### ISSUE TITLE
Question: Has aster already been used in production?

### ISSUE THREAD

**Issue by choleraehyq** [wayslog/aster#12]
Just out of curious.

**Comment by RuralDependencies** [comment]
Also very interested to replace twemproxy

**Comment by wayslog** [comment]
Yes, we had deployed `aster` in production environments in bilibili.com. Compares with [overlord](https://github.com/bilibili/overlord), and we eventually reduced the memory by 80% and cpu by 60%.

**Comment by wayslog** [comment]
> Also very interested to replace twemproxy

twemproxy mode(called standalone mode in aster) now only supports `fnv1a_64` hash method and ketama distribution. Maybe you need to implement the hash method which you want to use.

**Comment by choleraehyq** [comment]
@wayslog Then why is aster being open-sourced under your private account rather than [bilibili organization](https://github.com/bilibili/)? No offence.

**Comment by wayslog** [comment]
Because aster was developed in my free time. In fact, it's a personal project. But also suitable for our business usage.
