### ISSUE TITLE
Aster doesn't support DNS names in server list

### ISSUE THREAD

**Issue by AngerM** [wayslog/aster#26]
EX: for elasticache I can't pass in a server name of the cluster config endpoint for the server list. This is due to the fact that aster uses the `SocketAddr.parse` method instead of `to_socket_addrs`. I am new to rust, but have it kind of working with the following:
```
diff --git a/src/proxy/cluster.rs b/src/proxy/cluster.rs
index 4f3d08c..8f8669b 100644
--- a/src/proxy/cluster.rs
+++ b/src/proxy/cluster.rs
@@ -30,7 +30,7 @@ use tokio_codec::Decoder;
 
 use std::cell::{Cell, RefCell};
 use std::collections::{HashMap, HashSet, VecDeque};
-use std::net::SocketAddr;
+use std::net::{SocketAddr, ToSocketAddrs};
 use std::process;
 use std::rc::{Rc, Weak};
 use std::time::{Duration, Instant};
@@ -663,10 +663,12 @@ impl ConnBuilder {
                 let node_clone = node_addr.clone();
                 node_addr
                     .as_str()
-                    .parse()
+                    .to_socket_addrs()
                     .map_err(|err| error!("fail to parse addr {} due to {:?}", node_clone, err))
             })
-            .and_then(|addr| {
+            .and_then(|addrs| {
+                let collected: Vec<SocketAddr> = addrs.collect();
+                let addr = collected.first().unwrap();
                 let report_addr = format!("{:?}", &addr);
                 TcpStream::connect(&addr)
                     .timeout(Duration::from_millis(100))
```
Not sure if there is a better way to do that.

**Comment by wayslog** [comment]
Eureka!
I'd like to known that if you want aster parse the really ip from a given name by DNS resolver, is that?
It's a good idea, I will fix it as soon as possible.

**Comment by AngerM** [comment]
Correct. The example use case is putting aster in front of an AWS Elasticache cluster, for which we are not given the direct ip addresses to connect to, just the dns name.

**Comment by l2dy** [comment]
Does the domain resolve to a static IP address? If the IP address may change while Aster is running, we need to implement dynamic DNS resolution.

**Comment by AngerM** [comment]
That's true, but only if you lose the entire cluster at the same time. Otherwise you should always have sentinel or another shard whose info you would have gotten after the initial resolution and you should re-learn whatever replacements come online.

**Comment by wayslog** [comment]
The implement was in PR #27 .
